source "$ZSHHOME/rc/settings.zsh"
source "$ZSHHOME/rc/application_settings.zsh"
source "$ZSHHOME/rc/aliases.zsh"
source "$ZSHHOME/rc/aliases_git.zsh"
source "$ZSHHOME/rc/abbreviations.zsh"
source "$ZSHHOME/rc/functions.zsh"
source "$ZSHHOME/rc/hooks.zsh"
source "$ZSHHOME/rc/prompt.zsh"
source "$ZSHHOME/rc/postlude.zsh"
[[ -f "$HOME/.zshrc.local" ]] && source "$HOME/.zshrc.local"
