repo = "s3:https://s3.us-west-001.backblazeb2.com/uasi-backups/restic/home-notes"

[backup]
args = [
  "--skip-if-unchanged",
]

[forget]
args = [
  "--keep-within=1h",
  "--keep-within-hourly=7d",
  "--keep-within-daily=1m",
  "--keep-within-monthly=1y",
  "--compact",
  "--prune",
]

[[targets]]
tag = "logseq"
path = "~/Library/Mobile Documents/iCloud~com~logseq~logseq/Documents"

[[targets]]
tag = "obsidian"
path = "~/Library/Mobile Documents/iCloud~md~obsidian/Documents"
