repo = "~/Dropbox/Data/restic/repos/work-tmp"

[backup]
args = [
  "--skip-if-unchanged",
]

[forget]
args = [
  "--keep-within-hourly=1d",
  "--keep-within-daily=3d",
  "--compact",
  "--prune",
]

[[targets]]
tag = "tmp"
path = "~/tmp"
