repo = "~/Dropbox/Data/restic/repos/work-notes"

[forget]
args = [
  "--keep-within=1h",
  "--keep-within-hourly=7d",
  "--keep-within-daily=1m",
  "--keep-within-monthly=1y",
  "--compact",
  "--prune",
]

[[targets]]
tag = "logseq"
path = "~/Documents/Logseq"

[[targets]]
tag = "obsidian"
path = "~/Documents/Obsidian"
