theme = "base16_terminal"

[editor]
end-of-line-diagnostics = "hint"

[editor.inline-diagnostics]
other-lines = "hint"

[editor.whitespace.render]
tab = "all"

[keys.normal]
"0" = "goto_line_start"
"$" = "goto_line_end"
"D" = "kill_to_line_end"

[keys.select]
"$" = "goto_line_end"
"D" = "kill_to_line_end"
