[[language]]
name = "inko"
scope = "source.inko"
file-types = ["inko"]
roots = ["inko.pkg"]
indent = { tab-width = 2, unit = "  " }

[[language]]
name = "swift"
indent = { tab-width = 2, unit = "  " }
