"$schema" = "https://jj-vcs.github.io/jj/latest/config-schema.json"

[user]
name = "Tomoki Aonuma"
email = "uasi@uasi.jp"

[aliases]
abandon-blank = ["abandon", "-r", "blank() & mutable() ~ @"]
collapse-to = ["util", "exec", "--", "bash", "-c", 'jj squash --from "$1..${2:-@}" --into "$1"', "arg0"]
tug = ["bookmark", "advance"]

[revsets]
bookmark-advance-to = "closest_pushable(@)"

[revset-aliases]
"blank()" = "(empty() ~ merges() ~ root()) & description(exact:'')"
"meaningful()" = "(~empty() | merges()) ~ description(exact:'')"
"wip()" = "description(glob-i:'wip[: ]*')"
"wip_head(x)" = "heads(::x & wip())"
"wip_root(x)" = "roots(::x & wip())"

"closest_pushable(to)" = "heads(::to & mutable() & meaningful())"

# Doesn't work: https://github.com/jj-vcs/jj/issues/8311
"files_beyond(fileset)" = "files(fileset) & files(~fileset)"
"files_only(fileset)" = "files(fileset) ~ files(~fileset)"

# Doesn't work: https://github.com/jj-vcs/jj/issues/8311
"ensure_isolated(fileset, domain)" = "exactly(domain & files_beyond(fileset), 0)"
"files_extractable(fileset, domain)" = """
coalesce(
  ensure_isolated(fileset, domain),
  domain & files_only(fileset),
)
"""

"private_commits()" = "private_commits_base() | private_commits_extra()"
"private_commits_base()" = "wip() | description(glob:'// *')"
"private_commits_extra()" = "none()" # This allows for per-project overrides

# Command-line use only. Don't nest in other aliases to keep them easy to reason about.
"local()" = "all() ~ ::remote_bookmarks() ~ blank()"
"my_local()" = "mine() ~ ::remote_bookmarks() ~ blank()"
"untitled()" = "description(exact:'') ~ root()"

[git]
private-commits = "private_commits()"

[ui]
default-command = "status"
diff-editor = ":builtin"

[fix.tools.gofmt]
command = ["gofmt"]
patterns = ["glob:**/*.go"]

[fix.tools.cargo-fmt]
command = ["jj-fix-wrap", "--file=$file", "--in-place", "cargo", "fmt", "--", "%input"]
patterns = ["glob:**/*.rs"]

[fix.tools.swift-format]
command = ["swift-format", "format", "--ignore-unparsable-files", "-"]
patterns = ["glob:**/*.swift"]

[[--scope]]
--when.repositories = ["~/repos/github.com"]
[--scope.git]
sign-on-push = true
[--scope.signing]
backend = "ssh"
behavior = "drop"
key = "~/.ssh/id_ed25519_signing.pub"

[[--scope]]
--when.platforms = ["macos"]
[--scope.signing]
backends.ssh.program = "/Applications/1Password.app/Contents/MacOS/op-ssh-sign"
