[tools]
deno = "latest"
elixir = "latest"
node = "lts"
"pipx:archivebox" = "latest"
python = "latest"
ruby = "latest"
usage = "latest"
uv = "latest"


[settings]
experimental = true

[settings.pipx]
uvx = true
